### ISSUE TITLE
create_rpp is not working.

### ISSUE THREAD

**Issue by smartnav** [Dexus/paypal-ec2#11]
Hi,

I'm facing the problem with this api. Every time error come: 
{ TIMESTAMP: '2017-06-08T14:24:41Z',
  CORRELATIONID: 'f23913d96c4c2',
  ACK: 'Failure',
  VERSION: '78.0',
  BUILD: '29297572',
  L_ERRORCODE0: '11581',
  L_SHORTMESSAGE0: 'Invalid Data',
  L_LONGMESSAGE0: 'Profile description is invalid',
  L_SEVERITYCODE0: 'Error' }

My input is:  { PROFILESTARTDATE: '2017-06-08T14:24:40.336Z',
  PROFILEREFERENCE: '58e4e11786a16b4745bcac7b',
  DESC: '1009.00 USD Per month',
  BILLINGPERIOD: 'Day',
  BILLINGFREQUENCY: '1',
  AMT: '1009.00',
  CURRENCYCODE: 'USD',
  COUNTRYCODE: 'US',
  MAXFAILEDPAYMENTS: '3',
  TOKEN: 'EC-6MK9624456761251Y',
  PAYERID: 'LBXZX8XR92RGY',
  METHOD: 'createRecurringPaymentsProfile',
  USER: ,
  PWD: ,
  SIGNATURE: 'AFcWxV21C7fd0v3bYYYRCpSSRl31A3F.mkF.Z0hI2XlJxJX5IgXkRg9V',
  VERSION: '78.0' }

Note my description is same as in  doExpressCheckoutPayment.

 L_BILLINGAGREEMENTDESCRIPTION0: '1009.00 USD Per month',

Please check its urgent.
Thanks in advance.

**Comment by Dexus** [comment]
I'm sure `BILLINGPERIOD: 'Day',` did not match right?
